# Generated by Django 3.0.7 on 2020-06-10 19:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(default=True, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
