# Generated by Django 3.0.7 on 2020-06-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_post_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
