# Generated by Django 3.0.7 on 2020-06-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200610_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(default='htttp://', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.BooleanField(),
        ),
    ]
