# Generated by Django 3.0.7 on 2020-06-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='author',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_picture_url',
            field=models.URLField(default='http://', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=False, unique=True),
            preserve_default=False,
        ),
    ]
