# Generated by Django 3.0.7 on 2020-06-11 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200611_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='profile_picture_url',
            new_name='profile_picture',
        ),
    ]
